### ISSUE TITLE
Welcome page

### ISSUE THREAD

**Issue by luiscmartinez** [huskies-computer-club/east-club-site#1]
This should welcome new visitors. I circled some common html tags used, but I listed the specific ones you will need to complete this task on the todo list below.
![image](https://github.com/huskies-computer-club/east-club-site/assets/36746854/8c64ec9c-183c-4295-90fd-9ed2696e6a4b)

https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Getting_started

# Todo List:
- [ ]  Change the website’s tab name to ' East Computer Club ' use the `<title>` element to complete this task. Read it's usage here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/title
- [ ]  Greet the end user using the `<h1>` element. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements
Greeting should say “Reached: East Computer Club”
- [ ]  Add a summary using the `<h2>` 
Summary should say “A non-profit that serves as the ultimate equalizer for true education.”

**Comment by KenTen-21** [comment]
``<!DOCTYPE html>
<html lang="en">
  
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>East Computer Club</title>
    
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" />

  </head>
  
  <body>
    <h1>Reached: East Computer Club</h1>
    <h2> A non-profit that serves as the ultimate equalizer for true education</h2>
  </body>

First 3 Todo List

**Comment by luiscmartinez** [comment]
@KenTen-21 looks good. May you please put that inside an html file. 
To get this done follow these steps first. [Follow the steps here](https://milliongrad.notion.site/Getting-Started-on-Contributing-7066a2cc03a84a57be3a9a348a93e4ff?pvs=4)
