### ISSUE TITLE
Navigation Additions

### ISSUE THREAD

**Issue by luiscmartinez** [huskies-computer-club/east-club-site#11]
## Description:
Let's start to define a fleshed out navigation element. Just how you previously added the Register link now add a few more to complete the navigation element.
Make sure to get orientated with [getting started with css doc](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/CSS_basics)

### Todos:
- [x]  Add navigation link to home or index it should display “Home”
- [x]  Add navigation link to login.html it should display "Login"
- [x]  Create a `index.css` file then `link` element to import the css. [Read the link docs here ](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link)
- [ ]  Give the nav element a back border 2 pixels wide. [css border reference doc](https://developer.mozilla.org/en-US/docs/Web/CSS/border)

**Comment by KenTen-21** [comment]
![Screenshot (181)](https://github.com/huskies-computer-club/east-club-site/assets/132963840/fec83fa7-4f47-4afd-bc93-29a597f0e44f)
Added navigation links for home or index and added link to login.html, created  index.css file and the link to import the css, and the nav element for a back border 2 pixels wide.
