### ISSUE TITLE
Adds JavaScript to Form 

### ISSUE THREAD

**Issue by luiscmartinez** [huskies-computer-club/east-club-site#12]
## Description
Up to this point you have created a registration form using HTML elements, and made it pretty with CSS. You learned that elements have preconfigured attributes that results in different behavior. For example making the password input hide its content by simply changing its type value, and making the form display an error message when an input field is required. 

Your task is now to give the form a custom behavior. 

## User Story

When the user fills out the form but their password and conform password do not match the user should not be able to submit. Instead an error message should appear saying “passwords do not match”

### Todo list

- [ ]  Create a new javascript file, name it `registration.js`
- [ ]  Link the javascript file into your html page using the `<script>` element read the element reference here [https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attributes)
- [ ]  Define an eventlistener https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/submit_event
- [ ]  Inside the event listener function define a variable that stores the value of the password and confirm password input value. Compare them if they don’t have don’t allow the user to submit. [Using DOM Selectors](https://developer.mozilla.org/en-US/docs/Web/API/Document_object_model/Locating_DOM_elements_using_selectors)
