### ISSUE TITLE
Registration Page Enhancements 

### ISSUE THREAD

**Issue by luiscmartinez** [huskies-computer-club/east-club-site#8]
Now that we got a registration page, we must force the end user to behave correctly. 
For form related tasks [read/use this reference page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form)
For css related task [read/ use this element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link)
## Todo#1

<img width="293" alt="Screen Shot 2023-11-11 at 9 01 52 PM" src="https://github.com/huskies-computer-club/east-club-site/assets/36746854/d2f5cd61-e10c-4861-8f5d-cd4a43ae4c90">

- [ ] End user shouldn't be able to submit without filling out all the text inputs first. Make all the inputs required. Hint: add an attribute
## Todo#2
<img width="471" alt="Screen Shot 2023-11-11 at 9 13 28 PM" src="https://github.com/huskies-computer-club/east-club-site/assets/36746854/e6112eb1-00d0-48ac-a0db-d724f17096ef">

- [ ] The end user's password shouldn't display. Hint: change the input type
## Todo#3

- [ ] Create a `registration.css` file and add the everything inside the `style` element element

**Comment by luiscmartinez** [comment]
closed by #9
